#!/bin/sh

case "$1" in
    start)
        echo "Loading scull module"
        modprobe scull || exit 1

        major=$(awk '$2=="scull" {print $1}' /proc/devices)

        rm -f /dev/scull /dev/scull[0-3]
        mknod /dev/scull0 c $major 0
        mknod /dev/scull1 c $major 1
        mknod /dev/scull2 c $major 2
        mknod /dev/scull3 c $major 3
        ln -sf scull0 /dev/scull
        ;;

    stop)
        echo "Unloading scull module"
        rmmod scull
        rm -f /dev/scull /dev/scull[0-3]
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
