#!/bin/sh

case "$1" in
    start)
        echo "Loading aesdchar module"
        modprobe aesdchar || exit 1

        major=$(awk '$2=="aesdchar" {print $1}' /proc/devices)

        [ -n "$major" ] || exit 1

        rm -f /dev/aesdchar
        mknod /dev/aesdchar c $major 0
        chmod 664 /dev/aesdchar
        ;;

    stop)
        echo "Unloading aesdchar module"
        rmmod aesdchar || exit 1
        rm -f /dev/aesdchar
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
